"""add workspace_path to runs

Revision ID: 0ee897bfd02e
Revises: 180f15f2fefb
Create Date: 2026-03-31 12:49:39.216570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee897bfd02e'
down_revision: Union[str, Sequence[str], None] = '180f15f2fefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_path', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('workspace_path')

    # ### end Alembic commands ###
