"""initial schema

Revision ID: 5a9668ff4ada
Revises: 
Create Date: 2026-03-24 20:24:37.477216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9668ff4ada'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('pipeline_name', sa.String(), nullable=False),
    sa.Column('user_story', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('max_iterations', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('iteration_num', sa.Integer(), nullable=True),
    sa.Column('step_num', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iterations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('iteration_num', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'iteration_num')
    )
    op.create_table('code_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('iteration_num', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id', 'iteration_num'], ['iterations.run_id', 'iterations.iteration_num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('iteration_num', sa.Integer(), nullable=False),
    sa.Column('step_num', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=True),
    sa.Column('rework_seq', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id', 'iteration_num'], ['iterations.run_id', 'iterations.iteration_num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'iteration_num', 'step_num')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('iteration_num', sa.Integer(), nullable=False),
    sa.Column('step_num', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('artifact_type', sa.String(), nullable=True),
    sa.Column('artifact_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id', 'iteration_num', 'step_num'], ['steps.run_id', 'steps.iteration_num', 'steps.step_num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifacts')
    op.drop_table('steps')
    op.drop_table('code_files')
    op.drop_table('iterations')
    op.drop_table('events')
    op.drop_table('runs')
    op.drop_table('projects')
    # ### end Alembic commands ###
