"""add indexes on FK columns

Revision ID: b8e51bb17c31
Revises: 5a9668ff4ada
Create Date: 2026-03-25 00:36:54.475427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e51bb17c31'
down_revision: Union[str, Sequence[str], None] = '5a9668ff4ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_run_id', ['run_id'], unique=False)

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_runs_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_status')
        batch_op.drop_index('ix_runs_project_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_run_id')

    # ### end Alembic commands ###
